#!/usr/bin/env bash
# install nginx on remote server

apt-get update
apt-get upgrade
apt-get install -y nginx
mkdir /var/www/nginx/html
touch /var/www/nginx/html/index.html
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
    listen 80 defualt_server;
    listen [::]:80 defualt_server;
    root /etc/nginx/html;
    index  index.html;
}" > /etc/nginx/sites-avaliable/default
service nginx restart