#!/usr/bin/env bash
# Script gives info on file
file="school"

if [ -e "$school" ]; then
    echo "$school file exists"
    else
    echo "$school file does not exist"
    if [ -s "$school" ]; then
	echo "$school file is not empty"
    else
	echo "$school file is empty"
    if [ -f "$school" ]; then
	echo "$school is a regular file"  
