#!/usr/bin/env bash
# Bash script that uses ssh to connect to a server passphrase betty
# private key ~/.ssh/school; user ubuntu; host IP given as 35.229.54.225

ssh -i ~/.ssh/school ubuntu@13.38.104.226