#!/usr/bin/env bash
# Configure server with: Nginx, custom 404, custom 301 redirect to google
# Add to HTTP header

apt-get update
apt-get upgrade
apt-get install -y nginx
mkdir -p /etc/www/nginx/html
sudo touch /etc/www/nginx/html/index.html
sudo echo "Hello World!" > /etc/www/html/index.html
sudo echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
sudo echo "server {
    add_header X-Served_By $HOSTNAME;
    location /redirect_me {
        returning 301 http://daeshov.tech/;
    }
     error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    listen 80 defualt_server;
    listen [::]:80 defualt_server;
    root /etc/nginx/html;
    index  index.html;
}" > /etc/nginx/sites-avaliable/default
service nginx restart