#!/usr/bin/env bash
# install load bal


apt-get update
apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
cat <<EOT > /etc/haproxy/haproxy.cfg
defaults
    mode    http
frontend http-in
    bind    *:80
    default_backend questionTwo
backend questionTwo
    balance roundrobin
    server 5571-web-01 13.38.104.226:80 check
    server 5571-web-02 13.37.235.208:80 check
EOT
sudo service haproxy restart